### model
model_name_or_path: ./Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: sharegpt_data_chat_scene_32_images
template: qwen2_vl
cutoff_len: 32768
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
tokenized_path: ./tokenizer/sharegpt_data_chat_scene_32_images_pretokenized_data_img512
image_resolution: 512

### output
output_dir: outputs/qwen2vl_full_sft_nomark_32_img512/
logging_steps: 10
save_steps: 4000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 1.0
freeze_vision_tower: false
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

